### PR TITLE
Adding FDR benchmark comparison in comp bio

### PR DESCRIPTION
**Pull request by stephaniehicks**
Tagging lead authors @pkimes @kdkorthauer to ask if they want to add anything else

Please complete the following fields to make the reviewing process of the Pull Request as smooth as possible.

**Title (with link):**

**Authors (first authors, then et al.):**

**(Short) Description:**

**Tools/methods tested:**

**Recommendation(s) (can specify by metric, e.g. most performant, most accurate, etc.):**

Please make sure to append your name & GitHub profile info in the Contributors section of the README.md file!

### CODE REVIEW

**Comment by stephaniehicks** [comment]
Tagging lead authors @pkimes @kdkorthauer to ask if they want to add anything else

**Comment by kdkorthauer** [comment]
Looks great, @stephaniehicks! Thanks for adding!

**Comment by j-andrews7** [comment]
An excellent addition, thanks!

**Comment by pkimes** [comment]
Agree - looks great @stephaniehicks! Thanks!

**Pull request merged**
